# Generated by Django 4.0.1 on 2022-01-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_instructor_total_learners_alter_instructor_full_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(default=1),
        ),
    ]
