# Generated by Django 4.0.1 on 2022-03-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_submission_question_submission_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='lesson',
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
            preserve_default=False,
        ),
    ]
